config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post 'approve'
      post 'deny'
    end
  end
  resources :users, only: [:new, :create, :show]
  resource :session
  delete 'logout/:id', to: "Sessions#logout", as: :logout
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id
  COLORS = %w(black brown white yellow)
  validates :age, :birth_date, :color, :name, :sex, :user_id, presence: true
  validates :age, numericality: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: %w(M F)}

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status

  validates :cat_id, :start_date, :end_date, :status, :presence => true
  validates :cat_id, numericality: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  validate :no_overlapping_approved_requests

  before_validation :pending_status

  belongs_to(
    :cat,
    class_name: "Cat",
    foreign_key: :cat_id,
    primary_key: :id
  )

  def overlapping_requests
    range = [start_date..end_date]
    cat_requests = CatRentalRequest.where(cat_id: self.cat_id)
    start_overlaps = cat_requests.where(start_date: range)
    end_overlaps = cat_requests.where(end_date: range)

    start_overlaps + end_overlaps
  end

  def overlapping_approved_requests
    overlapping_requests.select { |req| req.status == "APPROVED" }
  end

  def no_overlapping_approved_requests
    unless overlapping_approved_requests.empty?
      errors[:base] << "That cat is already reserved"
    end
  end

  def pending_status
    self.status ||= "PENDING"
  end

  def overlapping_pending_requests
    overlapping_requests.select { |req| req.status == 'PENDING' }
  end

  def approve!
    transaction do
      self.status = 'APPROVED'
      self.save!
      overlapping_pending_requests.each do |req|
        req.deny! unless req.id = self.id
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == 'PENDING'
  end
end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :ip_address, :user_agent, :user_id, :token

  validates :ip_address, :user_agent, :user_id, :token, presence: true

  before_validation :set_token

  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )
  def set_token
    self.token ||= generate_token
  end

  def generate_token
    SecureRandom.base64
  end

  def self.delete_session_by_token(token)
    sess = Session.find_by_token(token)
    sess.destroy unless sess.nil?

    nil
  end

  def location
    geo = Geocoder.search(self.ip_address).first
    "#{geo.city}, #{geo.state_code}, #{geo.country_code}"
  end
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :user_name, :password_digest, :session_token


  validates :user_name, :password_digest, :session_token, presence: true
  validates :user_name, :session_token, uniqueness: true

  has_many(
    :cats,
    class_name: "Cat",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :sessions,
    class_name: 'Session',
    foreign_key: :user_id,
    primary_key: :id
  )

  before_validation :set_session_token

  def self.find_by_credentials(user_name, pwd)
    user = User.find_by_user_name(user_name)
    user if user.nil? || user.is_password?(pwd)
  end

  def password=(pwd)
    self.password_digest = BCrypt::Password.create(pwd)
  end

  def is_password?(pwd)
    BCrypt::Password.new(self.password_digest).is_password?(pwd)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper

  protect_from_forgery
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_filter :check_owner, only: [:approve, :deny]

  def new
  end

  def create
    rental = CatRentalRequest.new(params[:cat_rental_request])
    if rental.save
      redirect_to cat_path(rental.cat)
    else
      render text: "ERROR"
    end
  end

  def approve
    rental = CatRentalRequest.find(params[:id])
    rental.approve!
    redirect_to rental.cat
  end

  def deny
    rental = CatRentalRequest.find(params[:id])
    rental.deny!
    redirect_to rental.cat
  end

  def check_owner
    rental = CatRentalRequest.find(params[:id])
    redirect_to cats_url unless rental.cat.user_id == current_user.id
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :check_owner, only: [:edit, :update]
  before_filter :logged_in, only: [:edit, :update]
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(params[:cat])
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_path(@cat)
    else
      render :text => "Error"
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(params[:cat])
      redirect_to cat_path(@cat)
    else
      render 'edit'
    end
  end

  def check_owner
    @cat = Cat.find(params[:id])
    redirect_to cats_url unless @cat.user_id == current_user.id
  end

  def logged_in
    redirect_to cats_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(params[:session][:user_name], params[:session][:password])
    if user.nil?
      render :json => "Credentials were wrong"
    else
      login_user!(user)
      redirect_to cats_url
    end
  end

  def destroy
    if current_user
      Session.delete_session_by_token(session[:session_token])
      session[:session_token] = nil
    end
    redirect_to cats_url
  end

  def logout
    sess = Session.find(params[:id])
    if sess.user_id == current_user.id
      if sess.token == session[:session_token]
        session[:session_token] = nil
      end
      sess.destroy
    end
    redirect_to user_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    user = User.new
    user.user_name = params[:user][:user_name]
    user.password = params[:password]
    user.save
    login_user!(user)
    redirect_to cats_url
  end

  def show
    @user = current_user
    if @user.nil?
      redirect_to cats_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    @session ||= Session.find_by_token(session[:session_token])
    @current_user ||= @session.nil? ? nil : @session.user
  end

  def login_user!(user)
    @current_user = user
    @session = user.sessions.create(user_id: user.id, user_agent: request.env["HTTP_USER_AGENT"], ip_address: request.remote_ip)
    session[:session_token] = @session.token
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="/cat_rental_requests" method="POST">
  <label for="cat_id">Cat</label>
  <select name="cat_rental_request[cat_id]" id="cat_id">
    <% Cat.all.each do |cat| %>
    <option value="<%=cat.id%>"><%= cat.name %></option>
    <% end %>
  </select>
<br>
  <label for="start_date">Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" id="start_date">
<br>
  <label for="end_date">End Date</label>
  <input type="date" name="cat_rental_request[end_date]" id="end_date">
  <br>
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <input type="submit" value="Request Rental!">

</form>

app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<form action='<%= action_url %>' method="post">
  <% if cat.persisted? %>
  <input type="hidden" name="_method" value="PUT">
  <% end %>
  <label for"cat_name">Name</label>
  <input name="cat[name]" id="cat_name" type="text" value="<%= cat.name %>">
  <br>

  <label for"cat_age">Age</label>
  <input name="cat[age]" id="cat_age" type="number" value="<%= cat.age %>">
  <br>

  <label for"cat_birth_date">Birth Date</label>
  <input name="cat[birth_date]" id="cat_birth_date" type="date" value="<%= cat.birth_date %>">
  <br>
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">

  <label for"cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option value=""></option>
    <% Cat::COLORS.each do |color| %>
    <option value="<%= color %>" <%= "selected" if cat.color == color %>><%= color %></option>
    <% end %>
  </select>
  <br>

  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= "checked" if cat.sex == "F" %>>
  <label for="cat_sex_female">Female</label>
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= "checked" if cat.sex == "M" %>>
  <label for="cat_sex_male">Male</label>
  <br>

  <input type="submit" value="Create Cat">
</form>

app/views/cats/edit.html.erb
<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<h1>All Cats</h1>

<% @cats.each do |cat|%>

<%= link_to cat.name, cat_url(cat) %>

<%end%>

app/views/cats/new.html.erb
<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Age</th>
    <th>Color</th>
    <th>Sex</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

<h2>Requests</h2>

<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
    <th>Approve</th>
    <th>Deny</th>
  </tr>
  <% @cat.rental_requests.order(:start_date).each do |rental| %>
  <tr>
    <td><%= rental.start_date %></td>
    <td><%= rental.end_date %></td>
    <td><%= rental.status%></td>
    <% if rental.pending? && current_user.id == @cat.user_id %>
    <td><%= button_to "Approve", approve_cat_rental_request_url(rental), method: :post %></td>
    <td><%= button_to "Deny", deny_cat_rental_request_url(rental), method: :post %></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if !current_user.nil? %>
  <h1>Welcome <%= current_user.user_name %></h1>
  <%= link_to "Sessions", user_url(current_user) %>
  <%= button_to "Logout", session_url, :method => :delete %>
<% else %>
  <%= link_to "Log in", new_session_url %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action='/users' method= 'POST'>
  <label for="user_name">User Name</label>
  <input name="user[user_name]" type= "text">
  <br>

  <label for="password">Password</label>
  <input name="password" type="password">
  <br>
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <input type="submit" value="Create!">
</form>

app/views/users/show.html.erb
<h3>Sessions</h3>
<table>
  <tr>
    <th>User Agent</th>
    <th>IP Address</th>
    <th>Location</th>
    <th>Logout</th>
  </tr>
  <% @user.sessions.each do |sess| %>
  <tr>
    <td><%= sess.user_agent %></td>
    <td><%= sess.ip_address %></td>
    <td><%= sess.location%></td>
    <td><%= button_to "Logout", logout_path(sess), method: :delete%></td>
  </tr>
  <% end %>
</table>